name: solar_system
description: A solar system app/game.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.11.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  flutter_native_splash: ^2.4.7
  font_awesome_flutter: ^11.0.0
  faker: ^2.2.0
  signals: ^6.3.0
  signals_flutter: ^6.3.0
dev_dependencies:

flutter:
  uses-material-design: true
