// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'domain/models/load.dart';
import 'domain/models/panel.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5947939586222080557),
    name: 'Load',
    lastPropertyId: const obx_int.IdUid(3, 8481069850091346277),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6501507133887046237),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1640975322739842657),
        name: 'powerUsage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8481069850091346277),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 476960194934305973),
    name: 'Panel',
    lastPropertyId: const obx_int.IdUid(2, 1729978033304523104),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 477381313100712145),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1729978033304523104),
        name: 'powerCapacity',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1229923049378453407),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1229923049378453407],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      8401419522583034495,
      2424792787735869965,
      5168146185015165499,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Load: obx_int.EntityDefinition<Load>(
      model: _entities[0],
      toOneRelations: (Load object) => [],
      toManyRelations: (Load object) => {},
      getId: (Load object) => object.id,
      setId: (Load object, int id) {
        object.id = id;
      },
      objectToFB: (Load object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.powerUsage);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object =
            Load()
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..powerUsage = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                6,
                0,
              )
              ..name = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 8, '');

        return object;
      },
    ),
    Panel: obx_int.EntityDefinition<Panel>(
      model: _entities[1],
      toOneRelations: (Panel object) => [],
      toManyRelations: (Panel object) => {},
      getId: (Panel object) => object.id,
      setId: (Panel object, int id) {
        object.id = id;
      },
      objectToFB: (Panel object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.powerCapacity);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object =
            Panel()
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..powerCapacity = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                6,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Load] entity fields to define ObjectBox queries.
class Load_ {
  /// See [Load.id].
  static final id = obx.QueryIntegerProperty<Load>(_entities[0].properties[0]);

  /// See [Load.powerUsage].
  static final powerUsage = obx.QueryIntegerProperty<Load>(
    _entities[0].properties[1],
  );

  /// See [Load.name].
  static final name = obx.QueryStringProperty<Load>(_entities[0].properties[2]);
}

/// [Panel] entity fields to define ObjectBox queries.
class Panel_ {
  /// See [Panel.id].
  static final id = obx.QueryIntegerProperty<Panel>(_entities[1].properties[0]);

  /// See [Panel.powerCapacity].
  static final powerCapacity = obx.QueryIntegerProperty<Panel>(
    _entities[1].properties[1],
  );
}
